version: "3.8"
services:
  node:
    build: ./front
    volumes:
      - ./front:/app
    # command: sh -c 'cd react-app && yarn start'
    # command: npm start
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true